// File generated by Antigravity (Antigravity).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbnnviIsHdaliuTEDvqdybeXb1-sWq94',
    appId: '1:270649271058:web:YOUR_WEB_APP_ID_HERE', // Please replace this with your Web App ID
    messagingSenderId: '270649271058',
    projectId: 'project-1d052',
    authDomain: 'project-1d052.firebaseapp.com',
    storageBucket: 'project-1d052.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbnnviIsHdaliuTEDvqdybeXb1-sWq94',
    appId: '1:270649271058:android:14a86c3b99cc0edf3bc9cb',
    messagingSenderId: '270649271058',
    projectId: 'project-1d052',
    storageBucket: 'project-1d052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbnnviIsHdaliuTEDvqdybeXb1-sWq94',
    appId: '1:270649271058:ios:14a86c3b99cc0edf3bc9cb', // Likely similar to android, but best to re-verify
    messagingSenderId: '270649271058',
    projectId: 'project-1d052',
    storageBucket: 'project-1d052.firebasestorage.app',
    iosBundleId: 'com.example.faithwayy',
  );
}
